services:
  app:
    build: .
    container_name: quiniela_app
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      PORT: 8000
      APP_ENV: local
      APP_KEY: base64:vwoAnBy9OhRYk0iDu6dFy9elKh/Q+1cZox07Lb18wls=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: quiniela
      DB_USERNAME: quiniela
      DB_PASSWORD: secret
      CACHE_STORE: file
      SESSION_DRIVER: file
      FRONTEND_URL: http://localhost:3000
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      SANCTUM_STATEFUL_DOMAINS: localhost:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: quiniela_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quiniela
      POSTGRES_USER: quiniela
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quiniela"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
